### ISSUE TITLE
release tag 0.2.3 has incorrect version in shard.yml

### ISSUE THREAD

**Issue by damianham** [amberframework/garnet-spec#23]
adding garnet-spec to shard.yml with
```
development_dependencies:
  garnet_spec:
    github: amberframework/garnet-spec
    version: ~> 0.2.0
```
installs version 0.2.3 which has version 0.2.1 in it's shard.yml file, apparently causing this issue
https://github.com/crystal-lang/shards/issues/353
