### ISSUE TITLE
Version of selenium-webdriver-crystal uses a deprecated method

### ISSUE THREAD

**Issue by RenFontes** [amberframework/garnet-spec#24]
JSON.mapping is being used which is deprecated. 
Seems to be fixed in amberframework/selenium-webdriver-crystal but the version downloaded by garnet still has the issue.

Probably needs to be fixed here and on amberframework/selenium-webdriver-crystal.

**Comment by crimson-knight** [comment]
Yeah until I can do a few releases I'm currently using this `shard.override.yml`

```yml
dependencies:
  selenium:
    git: https://github.com/amberframework/selenium-webdriver-crystal.git
    branch: master

  garnet_spec:
    github: amberframework/garnet-spec
    branch: master
```
